# Generated by Django 5.2.9 on 2025-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='ema',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
